apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.local
      http:
        paths:
          # Route API calls to backend
          - pathType: ImplementationSpecific
            path: /api/(.*)
            backend:
              service:
                name: backend
                port:
                  number: 5000

          # Route all other traffic to frontend
          - pathType: ImplementationSpecific
            path: /(.*)
            backend:
              service:
                name: frontend
                port:
                  number: 80
