version: '3.8'

services:
  frontend:
    image: app-frontend 
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: app-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - data:/app
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
